# Site settings
title: Paul Brower's Portfolio
email: brower.paul@gmail.com
description: "Paul Brower, a Lead Android Developer with multiple years of experience creating excellent stable applications for clients big and small."
baseurl: ""
url: "http://github.com/browep"

# Build settings
markdown: kramdown
permalink: pretty
